[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "gym_unrealcv"
description = "Gymnasium environments for UnrealCV"
dynamic = ["version"]
requires-python = ">=3.9"
dependencies = [
    "gym==0.10.9",
    "matplotlib",
    "numpy",
    "onnxruntime",
    "unrealcv==1.3.2",
    "wget",
    "opencv-python",
    "glfw",
    "moderngl",
    "simple_pid",
    "pynput",
    "docker",
    "modelscope"
]
authors = [
    { name = "Fangwei Zhong", email = "zfw1226@gmail.com" },
    { name = "Kui Wu" }
]

[tool.setuptools.package-data]
"gym_unrealcv" = ["envs/setting/**/*"]

[tool.setuptools]

[tool.setuptools.packages.find]
include = ["gym_unrealcv*"]

[tool.setuptools.dynamic]
version = {attr = "gym_unrealcv.__version__"}
